spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 25
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
    drop-first: true
